export  const subscriptions = [
    {
        state : 'Malaysia',
        service : 'Data Only',
        service_type :'Postpaid',
        declaration_quarter :3,
        declaration_year :'2019',
        household :'Household',
        total_subs :40997,
    },
    {
        state : 'Johor',
        service : 'Data Only',
        service_type :'Postpaid',
        declaration_quarter :3,
        declaration_year :'2019',
        household :'Household',
        total_subs :40997,
    },
    {
        state : 'Kedah',
        service : 'Data Only',
        service_type :'Postpaid',
        declaration_quarter :3,
        declaration_year :'2019',
        household :'Household',
        total_subs :40997,
    },
    {
        state : 'Kelantan',
        service : 'Data Only',
        service_type :'Postpaid',
        declaration_quarter :3,
        declaration_year :'2019',
        household :'Household',
        total_subs :40997,
    },
    {
        state : 'Pahang',
        service : 'Data Only',
        service_type :'Postpaid',
        declaration_quarter :3,
        declaration_year :'2019',
        household :'Household',
        total_subs :40997,
    },
]